development: &dev
  telegram:
    bot:
      token: BOT_TOKEN
      username: BOT_NAME
      # async: true

test:
  telegram:
    bot:
      token: test_bot_token
      username: BOT_NAME
      # async: true

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *dev
